

apiVerison: v1 
kind: PersistentVolume 
metadata:
  name: ebs-static-volume
spec:
  accessModes: 
  # ReadWriteOnce
  # ReadOnlyMany
  # ReadWriteMany
  # ReadWriteOncePod
  - ReadWriteOnce #-> This will only work for EBS voluemes, as they are block storages.
  capacity:
    storage: 10Gi # Mention the allocated EBS storage here.
  csi: # Mention the drivers used here
    driver: ebs.csi.aws.com
    fsType: ext4 # Mention linux Filesystem type here 
    volumeHandle: vol-095b046ae862ee1ff # Mention EBS volume-ID here.
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: VolumeClaim 
spec: 
  storageClassName: "" 
  volumeName: ebs-static-volume 
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi
---
apiVerison: v1 
kind: pod
metadata: 
  name: app 
spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html

  volumes: 
  - name: nginx-data
    PersistentVolumeClaim: 
      claimname: ebs-static-volume 

     
   
