apiVersion: v1
kind: pod
metadata:
  name: multi-container-pod
  labels: # Labels are very important in kubernetes, Written in key_value pairs
    course: DevSecOps
    name: hello!
# namespace: <mentions a custom namespace to run the container>
spec:
  containers:
  - name: pod-1
    image: nginx
    ports:
    - containerPort: 80
  - name: pod-2
    imge: almalinux:8
    command: ["sleep","300"]    