apiVersion: v1
kind: pod
metadata: 
  name: Secret_pod
  label:
  annotation:
spec:
  containers:
  - name: pod1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: Secret01